import {
  LuGauge,
  LuMonitor,
  LuCupSoda,
  LuUtensils,
  LuMonitorCheck,
  LuMilkOff,
  LuArrowLeftRight,
  LuReceipt,
  LuUser,
  LuActivity,
  LuSettings,
  LuLogOut,
  LuMonitorCog,
} from "react-icons/lu";

export const SIDE_MENU_DATA = [
  {
    id: "01",
    label: "Dashboard",
    icon: LuGauge,
    path: "/dashboard",
  },
  {
    id: "02",
    label: "POS",
    icon: LuMonitor,
    path: "/dashboard/pos",
  },
  {
    id: "03",
    label: "Products",
    icon: LuCupSoda,
    path: "/dashboard/products",
  },
  {
    id: "04",
    icon: LuUtensils,
    label: "Ingredients & Materials",
    path: "/dashboard/ingredients",
  },
  {
    id: "05",
    icon: LuMonitorCheck,
    label: "Stock In",
    path: "/dashboard/stocks",
  },
  {
    id: "06",
    icon: LuMonitorCog,
    label: "Item Tracker",
    path: "/dashboard/tracker",
  },
  {
    id: "07",
    icon: LuMilkOff,
    label: "Spoiled & Damaged",
    path: "/dashboard/spoilage",
  },
  {
    id: "08",
    icon: LuArrowLeftRight,
    label: "Transactions",
    path: "/dashboard/transactions",
  },
  {
    id: "09",
    icon: LuReceipt,
    label: "Reports",
    path: "/dashboard/sales",
  },
  {
    id: "10",
    icon: LuUser,
    label: "Users",
    path: "/dashboard/users",
  },
  {
    id: "11",
    icon: LuActivity,
    label: "Activity Logs",
    path: "/dashboard/logs",
  },
  {
    id: "12",
    icon: LuSettings,
    label: "Settings",
    path: "/dashboard/settings",
  },
  {
    id: "13",
    icon: LuLogOut,
    label: "Logout",
    path: "logout",
  },
];
